# Generated by Django 3.2.24 on 2024-02-29 08:42

from django.db import migrations, models

def validate_phone_numbers(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.clean()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240229_1639'),
    ]

    operations = [
        migrations.RunPython(validate_phone_numbers),
    ]
