# Generated by Django 3.2.24 on 2024-03-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20240229_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_type',
            field=models.CharField(default='Unknown', editable=False, max_length=50),
        ),
    ]
